# Book settings
title: Actionable AI Ethics
author: Abhishek Gupta
copyright: "2021"
logo: abhishek.png

html:
  favicon: abhishek.png
  extra_navbar: You can support this work by <a href="https://buymeacoffee.com/abhishekgupta">buying me a coffee!</a>
  extra_footer: "Making Responsible AI the Norm rather than the Exception"
  baseurl: https://atg-abhishek.github.io/actionable-ai-ethics

# Information about where the book exists on the web
repository:
  url                       : https://github.com/atg-abhishek/actionable-ai-ethics
  branch                    : master  

launch_buttons:
  binderhub_url: https://mybinder.org

latex:
  latex_documents:
    targetname: book.tex

# sphinx:
#   extra_extensions:
#   - sphinxext.opengraph
#   config:
#     ogp_site_url: "https://atg-abhishek.github.io/actionable-ai-ethics"
#     ogp_image: "https://atg-abhishek.github.io/actionable-ai-ethics/_static/abhishek.png"
#     ogp_description_length: 200