# Book settings
title: Actionable AI Ethics
author: Abhishek Gupta
copyright: "2021"
logo: abhishek.png

html:
  favicon: abhishek.png
  extra_navbar: You can support this work by <a href="https://buymeacoffee.com/abhishekgupta">buying me a coffee!</a>
  extra_footer: "Making Responsible AI the Norm rather than the Exception"

# Information about where the book exists on the web
repository:
  url                       : https://github.com/atg-abhishek/actionable-ai-ethics
  branch                    : master  

launch_buttons:
  binderhub_url: https://mybinder.org

latex:
  latex_documents:
    targetname: book.tex
